#!/bin/bash

# Purpose : test typing normal characters and some backspace to stdin

source ./test/lib.sh

assert 'Hello'"$KEYS_BACKSPACE"'World' "HellWorld$"
assert 'Hello'"$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE"'World' "World$"
assert 'Hello'"$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE"'World' "World$"
assert 'HelloWorld'"$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE$KEYS_BACKSPACE" "$"
