language: C
os: osx
install:
    make
jobs:
  include:
    - stage: Basics
      script: ./test/author.sh
    - stage: Basics
      script: ./test/cli_append.sh
      script: ./test/cli_insert.sh
      script: ./test/cli_backspace.sh
      script: ./test/cli_delete.sh
notifications:
  email: false
  slack: 42born2code:cgvUOkdMpA1a8HqpKAQQz62J
